services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: attractions_db
      POSTGRES_USER: greaterr
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
